/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiPublicDownloadExtensionRouteImport } from './routes/api/public/download-extension'
import { Route as OauthGoogleMailReturnRouteImport } from './routes/oauth.google-mail.return'
import { Route as ApiPublicExtensionGenerateReplyRouteImport } from './routes/api/public/extension/generate-reply'
import { Route as ApiPublicExtensionStatusRouteImport } from './routes/api/public/extension/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadExtensionRoute =
  ApiPublicDownloadExtensionRouteImport.update({
    id: '/api/public/download-extension',
    path: '/api/public/download-extension',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthGoogleMailReturnRoute = OauthGoogleMailReturnRouteImport.update({
  id: '/oauth/google-mail/return',
  path: '/oauth/google-mail/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionGenerateReplyRoute =
  ApiPublicExtensionGenerateReplyRouteImport.update({
    id: '/api/public/extension/generate-reply',
    path: '/api/public/extension/generate-reply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionStatusRoute =
  ApiPublicExtensionStatusRouteImport.update({
    id: '/api/public/extension/status',
    path: '/api/public/extension/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/api/public/download-extension': typeof ApiPublicDownloadExtensionRoute
  '/oauth/google-mail/return': typeof OauthGoogleMailReturnRoute
  '/api/public/extension/generate-reply': typeof ApiPublicExtensionGenerateReplyRoute
  '/api/public/extension/status': typeof ApiPublicExtensionStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/api/public/download-extension': typeof ApiPublicDownloadExtensionRoute
  '/oauth/google-mail/return': typeof OauthGoogleMailReturnRoute
  '/api/public/extension/generate-reply': typeof ApiPublicExtensionGenerateReplyRoute
  '/api/public/extension/status': typeof ApiPublicExtensionStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/api/public/download-extension': typeof ApiPublicDownloadExtensionRoute
  '/oauth/google-mail/return': typeof OauthGoogleMailReturnRoute
  '/api/public/extension/generate-reply': typeof ApiPublicExtensionGenerateReplyRoute
  '/api/public/extension/status': typeof ApiPublicExtensionStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/guide'
    | '/privacy-policy'
    | '/terms'
    | '/api/public/download-extension'
    | '/oauth/google-mail/return'
    | '/api/public/extension/generate-reply'
    | '/api/public/extension/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/guide'
    | '/privacy-policy'
    | '/terms'
    | '/api/public/download-extension'
    | '/oauth/google-mail/return'
    | '/api/public/extension/generate-reply'
    | '/api/public/extension/status'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/guide'
    | '/privacy-policy'
    | '/terms'
    | '/api/public/download-extension'
    | '/oauth/google-mail/return'
    | '/api/public/extension/generate-reply'
    | '/api/public/extension/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  GuideRoute: typeof GuideRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicDownloadExtensionRoute: typeof ApiPublicDownloadExtensionRoute
  OauthGoogleMailReturnRoute: typeof OauthGoogleMailReturnRoute
  ApiPublicExtensionGenerateReplyRoute: typeof ApiPublicExtensionGenerateReplyRoute
  ApiPublicExtensionStatusRoute: typeof ApiPublicExtensionStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download-extension': {
      id: '/api/public/download-extension'
      path: '/api/public/download-extension'
      fullPath: '/api/public/download-extension'
      preLoaderRoute: typeof ApiPublicDownloadExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-mail/return': {
      id: '/oauth/google-mail/return'
      path: '/oauth/google-mail/return'
      fullPath: '/oauth/google-mail/return'
      preLoaderRoute: typeof OauthGoogleMailReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/generate-reply': {
      id: '/api/public/extension/generate-reply'
      path: '/api/public/extension/generate-reply'
      fullPath: '/api/public/extension/generate-reply'
      preLoaderRoute: typeof ApiPublicExtensionGenerateReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/status': {
      id: '/api/public/extension/status'
      path: '/api/public/extension/status'
      fullPath: '/api/public/extension/status'
      preLoaderRoute: typeof ApiPublicExtensionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  GuideRoute: GuideRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  ApiPublicDownloadExtensionRoute: ApiPublicDownloadExtensionRoute,
  OauthGoogleMailReturnRoute: OauthGoogleMailReturnRoute,
  ApiPublicExtensionGenerateReplyRoute: ApiPublicExtensionGenerateReplyRoute,
  ApiPublicExtensionStatusRoute: ApiPublicExtensionStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
